trigger_afi_build: # afi = axidraw for inkscape
  stage: test
  only:
    - master
  script: # it would be really cool to someday trigger the build and ask it to use the current plotink branch
    - echo "trigger a new build in the axidrawforinkscape pipeline"
    - curl -X POST -F token=4c216619153aa08744ce42abcfce45 -F ref=master https://gitlab.com/api/v4/projects/14623403/trigger/pipeline

.tests:
  artifacts:
    paths:
      - htmlcov
  script:
    - pip install .
    - pip install .['test'] .['dev']
    - echo "run tests"
    - coverage run -m unittest discover
    - coverage html

testpy2.7:
  extends: .tests
  image: "python:2.7"

testpy3.5:
  extends: .tests
  image: "python:3.5"

testpy3.6:
  extends: .tests
  image: "python:3.6"

testpy3.7:
  extends: .tests
  image: "python:3.7"
